name:
channels:
  - conda-forge
  - bioconda
  - bih-cubi # for bcl2fastq2
dependencies:
  - python=3.10
  - ca-certificates
  - openssl
  - python-dotenv
  - ipykernel
  - papermill # for running notebooks on CLI with parameters
  - bcl2fastq2 # only available on linux-64